# Naive Bayes with BoW data

Dữ liệu huấn luyện và kiểm tra sẽ được khởi tao sao cho về dạng vector đặc trưng sử dụng BoW

In [4]:
import numpy as np
from sklearn.naive_bayes import MultinomialNB

# train data
d1 = [2, 1, 1, 0, 0, 0, 0, 0, 0]
d2 = [1, 1, 0, 1, 1, 0, 0, 0, 0]
d3 = [0, 1, 0, 0, 1, 1, 0, 0, 0]
d4 = [0, 1, 0, 0, 0, 0, 1, 1, 1]

labels = np.array(['B', 'B', 'B', 'N'])

train_data = np.array([d1, d2, d3, d4])
print(train_data)

# test data
d5 = np.array([[2, 0, 0, 1, 0, 0, 0, 1, 0]])
d6 = np.array([[0, 1, 0, 0, 0, 0, 0, 1, 1]])

print('d5: ', d5)
print('d6: ', d6)

[[2 1 1 0 0 0 0 0 0]
 [1 1 0 1 1 0 0 0 0]
 [0 1 0 0 1 1 0 0 0]
 [0 1 0 0 0 0 1 1 1]]
d5:  [[2 0 0 1 0 0 0 1 0]]
d6:  [[0 1 0 0 0 0 0 1 1]]


## Train model NBC with MultinomialNB distribution

In [5]:
multinomial_NB = MultinomialNB()
multinomial_NB.fit(train_data, labels)

MultinomialNB()

## Predict d5 and d6 tests

In [6]:
print('Predicting class of d5: ' + str(multinomial_NB.predict(d5)[0]))
print('Predicting class of d5: ' + str(multinomial_NB.predict(d6)[0]))
print('Probality of d6 in each class: ' + str(multinomial_NB.predict_proba(d6)))

Predicting class of d5: B
Predicting class of d5: N
Probality of d6 in each class: [[0.29175335 0.70824665]]


## Using Bernoulli naive Bayes

Ta cần thay đổi một chút về các feature. Lúc này các giá trị khác không sẽ được đưa về 1 vì ta chỉ quan tâm từ đó có xuất hiện hay không.

In [7]:
from sklearn.naive_bayes import BernoulliNB
import numpy as np

# train data
d1 = [1, 1, 1, 0, 0, 0, 0, 0, 0]
d2 = [1, 1, 0, 1, 1, 0, 0, 0, 0]
d3 = [0, 1, 0, 0, 1, 1, 0, 0, 0]
d4 = [0, 1, 0, 0, 0, 0, 1, 1, 1]
train_data = np.array([d1, d2, d3, d4])
label = np.array(['B', 'B', 'B', 'N']) # 0 - B, 1 - N

# test data
d5 = np.array([[1, 0, 0, 1, 0, 0, 0, 1, 0]])
d6 = np.array([[0, 1, 0, 0, 0, 0, 0, 1, 1]])

## call MultinomialNB
model = BernoulliNB()
# training
model.fit(train_data, label)
# test
print('Predicting class of d5:', str(model.predict(d5)[0]))
print('Probability of d6 in each class:', model.predict_proba(d6))


Predicting class of d5: B
Probability of d6 in each class: [[0.16948581 0.83051419]]


Both of two models predict the same answer. Last probality do not affect to last decision